name: Test Zodiac Pipeline

on: workflow_dispatch

jobs:
  build-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install -r requirements.txt

      - name: 1. Download Assets
        run: python setup_assets.py

      - name: 2. Download Extras
        run: python setup_extras.py

      - name: 3. Generate Draft
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python generator_tarot.py

      - name: 4. Polish Script
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python choreographer.py

      - name: 5. Create Video
        run: python video_maker.py

      - uses: actions/upload-artifact@v4
        with:
          name: viral-tarot-video
          path: output_videos/*.mp4
